version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

version: "3"

# All available services
services:

  # Misc Storage
  postgres-db:
    restart: "always"
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      METABASE_PASSWORD: metabase
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54320:5432

  metabase:
    restart: "always"
    image: metabase/metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 54320
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      # Make sure the firewall at the database server allows connections to port 54320
      MB_DB_HOST: postgres-db
      MB_ENCRYPTION_SECRET_KEY: secretkey1234567
    ports:
      - 3000:3000

# Volumes to persist data
volumes:
  postgres_volume: