version: '3.0'

services:
  producer:
    build: ./
    container_name: kafka_producer_1
    restart: on-failure
    volumes:
      - ./data:/usr/src/app/datasets/
      - ./:/usr/src/app
    networks:
      - globalNetwork

networks:
  globalNetwork:
    external: true